const $=s=>document.querySelector(s), money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const defaults=[...window.STORE_PRODUCTS];
const products=JSON.parse(localStorage.getItem('lk_products')||'null')||defaults;
const durratProduct=products.find(p=>p.id==='durrat');
if(durratProduct)Object.assign(durratProduct,{gender:'Feminino',tone:'Oriental',accords:'Especiado quente · Amadeirado · Baunilha · Almiscarado · Atalcado · Aromático · Doce · Terroso · Balsâmico · Metálico',image:'assets/products/durrat-al-aroos.jpeg'});
const oudMysteryProduct=products.find(p=>p.id==='oud-mystery');
if(oudMysteryProduct)Object.assign(oudMysteryProduct,{gender:'Unissex',tone:'Amadeirado especiado',accords:'Oud · Especiado fresco · Especiado quente · Patchouli · Almiscarado · Lavanda · Metálico · Atalcado · Amadeirado · Terroso',image:'assets/products/oud-mystery-intense.jpeg'});
const salvoProduct=products.find(p=>p.id==='salvo');
if(salvoProduct)Object.assign(salvoProduct,{gender:'Masculino',tone:'Aromático fresco',accords:'Especiado fresco · Cítricos · Âmbar · Lavanda · Aromático · Almiscarado · Herbal · Floral · Anis · Especiado suave',image:'assets/products/salvo.jpeg'});
const clubNuitProduct=products.find(p=>p.id==='club-nuit');
if(clubNuitProduct)Object.assign(clubNuitProduct,{gender:'Masculino',tone:'Amadeirado cítrico',accords:'Cítrico · Frutado · Couro · Defumado · Amadeirado',notes:'Limão verdadeiro · Vidoeiro · Abacaxi · Bergamota · Almíscar · Groselha-preta',use:'Boa presença durante o dia e à noite, com longevidade aproximada de 8 horas e rastro forte.',image:'assets/products/club-de-nuit-intense.jpeg'});
const sabahProduct=products.find(p=>p.id==='sabah');
if(sabahProduct)Object.assign(sabahProduct,{gender:'Feminino',tone:'Floral oriental',accords:'Floral · Cítrico · Rosa · Jasmim · Baunilha · Almiscarado',notes:'Topo: frutas cítricas e acordes florais · Corpo: jasmim e rosa · Fundo: baunilha e almíscar',use:'Fragrância feminina envolvente, floral e delicada, com um toque oriental marcante.',image:'assets/products/sabah-al-ward.jpeg'});
const sakeenaProduct=products.find(p=>p.id==='sakeena');
if(sakeenaProduct)Object.assign(sakeenaProduct,{gender:'Feminino',tone:'Doce frutado floral',accords:'Doce · Frutado · Rosa · Tropical · Baunilha',use:'Versátil para o dia a dia, noites, encontros, eventos, trabalho e momentos especiais.',image:'assets/products/sakeena.webp'});
const petraProduct=products.find(p=>p.id==='petra');
if(petraProduct)Object.assign(petraProduct,{gender:'Unissex',tone:'Doce floral branco',accords:'Doce · Tuberosa · Baunilha · Coco · Floral branco',notes:'Tuberosa · Rum · Coco · Ameixa · Fava de baunilha · Almíscar',use:'Boa presença durante o dia e também à noite, com longevidade aproximada de 7 horas e rastro forte.',image:'assets/products/petra.jpeg'});
const fakharProduct=products.find(p=>p.id==='fakhar');
if(fakharProduct)Object.assign(fakharProduct,{gender:'Masculino',tone:'Amadeirado aromático',accords:'Âmbar · Tuberosa · Floral branco · Almíscar · Cítricos · Especiarias quentes · Madeiras · Couro',image:'assets/products/fakhar-gold.jpeg'});
const yaraProduct=products.find(p=>p.id==='yara');
if(yaraProduct)Object.assign(yaraProduct,{gender:'Feminino',tone:'Doce e cremoso',accords:'Doce · Baunilha · Atalcado · Tropical · Frutado · Almíscar · Floral · Cítricos',image:'assets/products/yara-rosa.jpeg'});
const queenProduct=products.find(p=>p.id==='queen');
if(queenProduct)Object.assign(queenProduct,{gender:'Feminino',tone:'Doce floral branco',accords:'Doce · Tuberosa · Baunilha · Coco · Floral branco',notes:'Tuberosa · Rum · Coco · Ameixa · Baunilha · Almíscar · Âmbar',use:'Versátil para o dia a dia, encontros, eventos, trabalho e ocasiões especiais.',image:'assets/products/queen-of-arabia.jpeg'});
const hayaProduct=products.find(p=>p.id==='haya');
if(hayaProduct)Object.assign(hayaProduct,{gender:'Feminino',tone:'Floral frutado',image:'assets/products/haya.jpeg'});
const asadBourbonProduct=products.find(p=>p.id==='asad-bourbon');
if(asadBourbonProduct)Object.assign(asadBourbonProduct,{gender:'Masculino',tone:'Oriental especiado',accords:'Baunilha · Cacau · Doce · Lavanda · Especiado fresco · Aromático · Âmbar · Especiado quente · Atalcado',image:'assets/products/asad-bourbon-nova.webp'});
const musamamProduct=products.find(p=>p.id==='musamam');
if(musamamProduct)Object.assign(musamamProduct,{name:'Musamam White Intense',gender:'Unissex',tone:'Oriental floral',accords:'Amadeirado · Especiado quente · Coco · Doce · Cítricos · Atalcado · Âmbar · Floral amarelo · Almiscarado · Baunilha',image:'assets/products/musamam-white-intense.webp'});
const asadBlackProduct=products.find(p=>p.id==='asad-black');
if(asadBlackProduct)Object.assign(asadBlackProduct,{gender:'Masculino',tone:'Oriental',accords:'Âmbar · Especiado fresco · Amadeirado · Baunilha · Especiado quente · Doce · Tabaco · Atalcado · Patchouli · Balsâmico',image:'assets/products/asad-black.jpg'});
const azzaroProduct=products.find(p=>p.id==='azzaro');
const kitYaraProduct=products.find(p=>p.id==='kit-yara-mini');
if(kitYaraProduct)Object.assign(kitYaraProduct,{name:'Kit Yara 5 ml',volume:'4 unidades de 5 ml',price:240,tone:'Seleção de miniaturas Yara',image:'assets/products/kit-yara-4x5ml.webp'});
const khamrahProduct=products.find(p=>p.id==='khamrah');
if(khamrahProduct)Object.assign(khamrahProduct,{gender:'Unissex',tone:'Oriental especiado',accords:'Doce · Especiado quente · Baunilha · Âmbar · Canela · Amadeirado · Especiado fresco · Frutado',image:'assets/products/khamrah.jpeg'});
if(azzaroProduct)Object.assign(azzaroProduct,{name:'Azzaro Pour Homme',gender:'Masculino',tone:'Aromático amadeirado',accords:'Aromático · Amadeirado · Especiado fresco · Terroso · Lavanda · Anis · Especiado suave · Musgo · Couro · Cítricos',image:'assets/products/azzaro-pour-homme.jpg'});
const decants=window.STORE_DECANTS, kits=window.STORE_KITS;
let cart=JSON.parse(localStorage.getItem('lk_cart')||'[]'), kitChoices=JSON.parse(localStorage.getItem('lk_kit_decantes')||'null')||['','','',''], active='Todos', query='';
const categories=['Todos','Feminino','Masculino','Unissex'];
const stockLimits={sabah:2,'club-nuit':1,salvo:1,'oud-mystery':1,durrat:1,sakeena:1,petra:1,fakhar:1,yara:1,queen:2,haya:2,'asad-bourbon':1,musamam:1,'asad-black':1,azzaro:2,'kit-yara-mini':1,khamrah:1};
const kitComponents={
  'kit-feminino':{queen:1,haya:1},
  'kit-casal':{azzaro:1,sabah:1},
  'kit-masculino':{azzaro:1,'club-nuit':1}
};

function productArt(p){if(p.image)return `<img class="product-photo" src="${p.image}" alt="${p.name} ${p.brand} com embalagem">`;const initials=p.name.split(' ').filter(x=>x.length>2).slice(0,2).map(x=>x[0]).join('');return `<div class="bottle-art"><span class="cap"></span><span class="bottle">${initials}</span></div>`}
function productExtra(p){if(!p.accords&&!p.notes)return '';return `<details class="product-notes"><summary>Ver perfil olfativo</summary>${p.accords?`<p><strong>Acordes:</strong> ${p.accords}</p>`:''}${p.notes?`<p><strong>Notas:</strong> ${p.notes}</p>`:''}${p.use?`<p><strong>Uso:</strong> ${p.use}</p>`:''}</details>`}
function productBadge(p){const limit=stockLimits[p.id];return limit===1?'Última unidade':limit===2?'2 unidades':p.badge}
function renderFilters(){ $('#filters').innerHTML=categories.map(c=>`<button class="chip ${c===active?'active':''}" data-filter="${c}">${c}</button>`).join('') }
function renderProducts(){let list=products.filter(p=>(active==='Todos'||p.gender===active)&&(`${p.name} ${p.brand} ${p.tone}`.toLowerCase().includes(query)));const sort=$('#sort').value;if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='featured')list.sort((a,b)=>Number(b.featured)-Number(a.featured));$('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual">${productArt(p)}<span class="badge">${productBadge(p)}</span></div><div class="product-info"><p>${p.brand}</p><h3>${p.name}</h3><span>${p.tone} · ${p.volume}</span>${productExtra(p)}<div class="product-bottom"><div><strong>${money(p.price)}</strong><small class="pix-price">${money(p.price*.95)} no Pix</small></div><button class="add" data-add="${p.id}" aria-label="Adicionar ${p.name}">+</button></div></div></article>`).join('');$('#emptyState').hidden=!!list.length}
function renderDecants(){ $('#decantGrid').innerHTML=decants.map(d=>`<article><span class="decant-vial"></span><div><small>DECANTE · 5 ML</small><h3>${d.name.replace('Decante ','')}</h3><strong>${money(d.price)} <em>por unidade</em></strong></div><button class="add small" data-add="${d.id}" aria-label="Adicionar ${d.name}">+</button></article>`).join('') }
function renderKits(){ $('#kitGrid').innerHTML=kits.map((k,i)=>{const pix=k.pixPrice??k.basePrice*.95,card=k.basePrice,mumbuca=k.mumbucaPrice;return `<article class="kit-card"><span class="kit-number">0${i+1}</span><p>Kit exclusivo</p><h3>${k.name}</h3><span>${k.description}</span><div class="kit-prices"><small>Valor do kit ${money(k.basePrice)}</small><strong>${money(pix)} <em>no Pix</em></strong>${mumbuca?`<b>${money(mumbuca)} na Mumbuca</b>`:''}<b>${money(card)} no cartão</b><small>ou 6x de ${money(card/6)} sem juros</small></div><button class="button outline full" data-kit="${k.id}">Quero este kit</button></article>`}).join('') }
function findItem(id){return products.find(p=>p.id===id)||decants.find(d=>d.id===id)}
function usedStock(productId){return cart.reduce((total,item)=>total+(item.id===productId?item.qty:0)+((kitComponents[item.id]?.[productId]||0)*item.qty),0)}
function canIncrease(item){const components=kitComponents[item.id];if(components)return Object.entries(components).every(([id,qty])=>usedStock(id)+qty<=stockLimits[id]);const limit=stockLimits[item.id];return !limit||usedStock(item.id)+1<=limit}
function stockWarning(item){const components=kitComponents[item.id];if(components){const unavailable=Object.entries(components).filter(([id,qty])=>usedStock(id)+qty>stockLimits[id]).map(([id])=>products.find(p=>p.id===id)?.name||id);return unavailable.length?`Estoque insuficiente para: ${unavailable.join(', ')}`:'Estoque insuficiente para este kit'}return 'Quantidade máxima disponível no estoque'}
function addItem(id){const item=findItem(id);if(!item)return;if(!canIncrease(item)){toast(stockWarning(item));return}const found=cart.find(x=>x.id===id);found?found.qty++:cart.push({...item,qty:1});save();toast(`${item.name} adicionado à sacola`)}
function save(){localStorage.setItem('lk_cart',JSON.stringify(cart));localStorage.setItem('lk_kit_decantes',JSON.stringify(kitChoices));renderCart()}
function pixEligible(x){return x.type!=='decant'}
function paymentPrice(x,payment){if(x.id==='kit-decantes-4'&&(payment==='Pix'||payment==='Mumbuca'))return 120;if(payment==='Pix'&&pixEligible(x))return x.price*.95;return x.price}
function totals(){const payment=document.querySelector('[name="payment"]:checked')?.value||'Pix';let subtotal=0,total=0;cart.forEach(x=>{const line=x.price*x.qty;subtotal+=line;total+=paymentPrice(x,payment)*x.qty});return {subtotal,total,discount:subtotal-total}}
function fullSizeCount(){return cart.filter(x=>x.type!=='decant'&&x.type!=='kit'&&x.volume!=='Kit').reduce((n,x)=>n+x.qty,0)}
function kitChoiceMarkup(){if(!cart.some(x=>x.id==='kit-decantes-4'))return '';const options=decants.map(d=>d.name.replace('Decante ',''));return `<div class="kit-choice"><h3>Escolha os 4 decantes</h3><p>Você pode repetir uma fragrância.</p>${kitChoices.map((choice,i)=>`<label>Fragrância ${i+1}<select data-kit-choice="${i}"><option value="">Selecione...</option>${options.map(name=>`<option ${choice===name?'selected':''}>${name}</option>`).join('')}</select></label>`).join('')}</div>`}
function renderCart(){const count=cart.reduce((n,x)=>n+x.qty,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><div><h3>${x.name}</h3><span>${x.volume||'Kit'} · ${money(x.price)}</span></div><div class="quantity"><button data-qty="${x.id}" data-delta="-1">−</button><b>${x.qty}</b><button data-qty="${x.id}" data-delta="1">+</button></div></div>`).join('')+kitChoiceMarkup():'<div class="cart-empty"><span>◇</span><p>Sua sacola está vazia.</p><a href="#catalogo" class="close-link">Explorar perfumes</a></div>';const t=totals();$('#cartTotal').textContent=money(t.total);const gifts=Math.floor(fullSizeCount()/3);$('#giftChoice').hidden=gifts<1;$('#giftSelect').innerHTML=decants.map(d=>`<option>${d.name.replace('Decante ','')}</option>`).join('');const notices=[];const payment=document.querySelector('[name="payment"]:checked')?.value||'Pix';if(t.discount)notices.push(`Economia no ${payment}: −${money(t.discount)}`);if(gifts)notices.push(`${gifts} decante${gifts>1?'s':''} grátis liberado${gifts>1?'s':''}`);$('#discountText').textContent=notices.join(' · ')}
function toggleCart(open){$('#cart').classList.toggle('open',open);$('#overlay').classList.toggle('show',open);$('#cart').setAttribute('aria-hidden',!open);document.body.classList.toggle('no-scroll',open)}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function checkout(){if(!cart.length){toast('Adicione um produto antes de finalizar');return}if(cart.some(x=>x.id==='kit-decantes-4')&&kitChoices.some(x=>!x)){toast('Escolha as 4 fragrâncias do Kit Decantes');return}const payment=document.querySelector('[name="payment"]:checked').value;let total=0;const lines=cart.map(x=>{const price=paymentPrice(x,payment);total+=price*x.qty;return `• ${x.name} — ${x.qty} un. — ${money(price*x.qty)}`});if(cart.some(x=>x.id==='kit-decantes-4'))lines.push(`  Fragrâncias: ${kitChoices.join(' · ')}`);const gifts=Math.floor(fullSizeCount()/3);if(gifts)lines.push(`🎁 Brinde: ${gifts}x Decante ${$('#giftSelect').value} 5 ml`);const notes=$('#notes').value.trim();const text=[`Olá! Gostaria de fazer este pedido na Lojinha da Karla:`,``,...lines,``,`Total estimado: ${money(total)}`,`Pagamento: ${payment}`,notes?`Observações: ${notes}`:'','',`Pode confirmar a disponibilidade e a entrega?`].filter(Boolean).join('\n');window.open(`https://wa.me/5521999000170?text=${encodeURIComponent(text)}`,'_blank')}

document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)addItem(add.dataset.add);const qty=e.target.closest('[data-qty]');if(qty){const x=cart.find(i=>i.id===qty.dataset.qty);if(x){const delta=Number(qty.dataset.delta);if(delta>0&&!canIncrease(x)){toast(stockWarning(x));return}x.qty+=delta;if(x.qty<=0)cart=cart.filter(i=>i.id!==x.id);save()}}const filter=e.target.closest('[data-filter]');if(filter){active=filter.dataset.filter;renderFilters();renderProducts()}const kit=e.target.closest('[data-kit]');if(kit){const k=kits.find(x=>x.id===kit.dataset.kit),item={id:k.id,name:k.name,price:k.basePrice,volume:'Kit',type:'kit',qty:1};if(!canIncrease(item)){toast(stockWarning(item));return}const found=cart.find(x=>x.id===k.id);found?found.qty++:cart.push(item);save();toggleCart(true)}if(e.target.closest('.close-link'))toggleCart(false)});
document.addEventListener('change',e=>{if(e.target.matches('[data-kit-choice]')){kitChoices[Number(e.target.dataset.kitChoice)]=e.target.value;localStorage.setItem('lk_kit_decantes',JSON.stringify(kitChoices))}});
$('#search').addEventListener('input',e=>{query=e.target.value.toLowerCase().trim();renderProducts()});$('#sort').addEventListener('change',renderProducts);document.querySelectorAll('[name="payment"]').forEach(r=>r.addEventListener('change',renderCart));$('#openCart').onclick=()=>toggleCart(true);$('#closeCart').onclick=()=>toggleCart(false);$('#overlay').onclick=()=>toggleCart(false);$('#checkout').onclick=checkout;$('.menu-button').onclick=e=>{const open=$('.nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)};document.querySelectorAll('.nav a').forEach(a=>a.onclick=()=>$('.nav').classList.remove('open'));$('#year').textContent=new Date().getFullYear();renderFilters();renderProducts();renderDecants();renderKits();renderCart();
