const $=s=>document.querySelector(s), money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const defaults=[...window.STORE_PRODUCTS];
const products=JSON.parse(localStorage.getItem('lk_products')||'null')||defaults;
const fakharProduct=products.find(p=>p.id==='fakhar');
if(fakharProduct)Object.assign(fakharProduct,{gender:'Masculino',tone:'Amadeirado aromático',accords:'Âmbar · Tuberosa · Floral branco · Almíscar · Cítricos · Especiarias quentes · Madeiras · Couro',image:'assets/products/fakhar-gold.jpeg'});
const yaraProduct=products.find(p=>p.id==='yara');
if(yaraProduct)Object.assign(yaraProduct,{gender:'Feminino',tone:'Doce e cremoso',accords:'Doce · Baunilha · Atalcado · Tropical · Frutado · Almíscar · Floral · Cítricos',image:'assets/products/yara-rosa.jpeg'});
const queenProduct=products.find(p=>p.id==='queen');
if(queenProduct)Object.assign(queenProduct,{gender:'Feminino',tone:'Doce floral branco',accords:'Doce · Tuberosa · Baunilha · Coco · Floral branco',notes:'Tuberosa · Rum · Coco · Ameixa · Baunilha · Almíscar · Âmbar',use:'Versátil para o dia a dia, encontros, eventos, trabalho e ocasiões especiais.',image:'assets/products/queen-of-arabia.jpeg'});
const hayaProduct=products.find(p=>p.id==='haya');
if(hayaProduct)Object.assign(hayaProduct,{gender:'Feminino',tone:'Floral frutado',image:'assets/products/haya.jpeg'});
const asadBourbonProduct=products.find(p=>p.id==='asad-bourbon');
if(asadBourbonProduct)Object.assign(asadBourbonProduct,{gender:'Masculino',tone:'Oriental especiado',accords:'Baunilha · Cacau · Doce · Lavanda · Especiado fresco · Aromático · Âmbar · Especiado quente · Atalcado',image:'assets/products/asad-bourbon.jpeg'});
const decants=window.STORE_DECANTS, kits=window.STORE_KITS;
let cart=JSON.parse(localStorage.getItem('lk_cart')||'[]'), active='Todos', query='';
const categories=['Todos','Feminino','Masculino','Unissex'];
const stockLimits={fakhar:1,yara:1,queen:2,haya:2,'asad-bourbon':1};

function productArt(p){if(p.image)return `<img class="product-photo" src="${p.image}" alt="${p.name} ${p.brand} com embalagem">`;const initials=p.name.split(' ').filter(x=>x.length>2).slice(0,2).map(x=>x[0]).join('');return `<div class="bottle-art"><span class="cap"></span><span class="bottle">${initials}</span></div>`}
function productExtra(p){if(!p.accords&&!p.notes)return '';return `<details class="product-notes"><summary>Ver perfil olfativo</summary>${p.accords?`<p><strong>Acordes:</strong> ${p.accords}</p>`:''}${p.notes?`<p><strong>Notas:</strong> ${p.notes}</p>`:''}${p.use?`<p><strong>Uso:</strong> ${p.use}</p>`:''}</details>`}
function productBadge(p){const limit=stockLimits[p.id];return limit===1?'Última unidade':limit===2?'2 unidades':p.badge}
function renderFilters(){ $('#filters').innerHTML=categories.map(c=>`<button class="chip ${c===active?'active':''}" data-filter="${c}">${c}</button>`).join('') }
function renderProducts(){let list=products.filter(p=>(active==='Todos'||p.gender===active)&&(`${p.name} ${p.brand} ${p.tone}`.toLowerCase().includes(query)));const sort=$('#sort').value;if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='featured')list.sort((a,b)=>Number(b.featured)-Number(a.featured));$('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual">${productArt(p)}<span class="badge">${productBadge(p)}</span></div><div class="product-info"><p>${p.brand}</p><h3>${p.name}</h3><span>${p.tone} · ${p.volume}</span>${productExtra(p)}<div class="product-bottom"><strong>${money(p.price)}</strong><button class="add" data-add="${p.id}" aria-label="Adicionar ${p.name}">+</button></div></div></article>`).join('');$('#emptyState').hidden=!!list.length}
function renderDecants(){ $('#decantGrid').innerHTML=decants.map(d=>`<article><span class="decant-vial"></span><div><small>DECANTE · 5 ML</small><h3>${d.name.replace('Decante ','')}</h3><strong>${money(d.price)} <em>por unidade</em></strong></div><button class="add small" data-add="${d.id}" aria-label="Adicionar ${d.name}">+</button></article>`).join('') }
function renderKits(){ $('#kitGrid').innerHTML=kits.map((k,i)=>{const pix=k.basePrice*.85,card=k.basePrice*.95;return `<article class="kit-card"><span class="kit-number">0${i+1}</span><p>Kit exclusivo</p><h3>${k.name}</h3><span>${k.description}</span><div class="kit-prices"><small>Valor de referência <s>${money(k.basePrice)}</s></small><strong>${money(pix)} <em>no Pix</em></strong><b>${money(card)} no cartão</b><small>ou 6x de ${money(card/6)} sem juros</small></div><button class="button outline full" data-kit="${k.id}">Quero este kit</button></article>`}).join('') }
function findItem(id){return products.find(p=>p.id===id)||decants.find(d=>d.id===id)}
function addItem(id){const item=findItem(id);if(!item)return;const found=cart.find(x=>x.id===id),limit=stockLimits[id];if(found&&limit&&found.qty>=limit){toast('Esta é a última unidade disponível');return}found?found.qty++:cart.push({...item,qty:1});save();toast(`${item.name} adicionado à sacola`)}
function save(){localStorage.setItem('lk_cart',JSON.stringify(cart));renderCart()}
function totals(){const payment=document.querySelector('[name="payment"]:checked')?.value||'Pix';let subtotal=0,total=0;cart.forEach(x=>{const line=x.price*x.qty;subtotal+=line;total+=(x.type==='kit'?x.price*(payment==='Pix'?.85:.95):x.price)*x.qty});return {subtotal,total,discount:subtotal-total}}
function fullSizeCount(){return cart.filter(x=>x.type!=='decant'&&x.type!=='kit'&&x.volume!=='Kit').reduce((n,x)=>n+x.qty,0)}
function renderCart(){const count=cart.reduce((n,x)=>n+x.qty,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><div><h3>${x.name}</h3><span>${x.volume||'Kit'} · ${money(x.price)}</span></div><div class="quantity"><button data-qty="${x.id}" data-delta="-1">−</button><b>${x.qty}</b><button data-qty="${x.id}" data-delta="1">+</button></div></div>`).join(''):'<div class="cart-empty"><span>◇</span><p>Sua sacola está vazia.</p><a href="#catalogo" class="close-link">Explorar perfumes</a></div>';const t=totals();$('#cartTotal').textContent=money(t.total);const gifts=Math.floor(fullSizeCount()/3);$('#giftChoice').hidden=gifts<1;$('#giftSelect').innerHTML=decants.map(d=>`<option>${d.name.replace('Decante ','')}</option>`).join('');const notices=[];if(t.discount)notices.push(`Desconto nos kits: −${money(t.discount)}`);if(gifts)notices.push(`${gifts} decante${gifts>1?'s':''} grátis liberado${gifts>1?'s':''}`);$('#discountText').textContent=notices.join(' · ')}
function toggleCart(open){$('#cart').classList.toggle('open',open);$('#overlay').classList.toggle('show',open);$('#cart').setAttribute('aria-hidden',!open);document.body.classList.toggle('no-scroll',open)}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function checkout(){if(!cart.length){toast('Adicione um produto antes de finalizar');return}const payment=document.querySelector('[name="payment"]:checked').value;let total=0;const lines=cart.map(x=>{let price=x.price;if(x.type==='kit')price*=payment==='Pix'?.85:.95;total+=price*x.qty;return `• ${x.name} — ${x.qty} un. — ${money(price*x.qty)}`});const gifts=Math.floor(fullSizeCount()/3);if(gifts)lines.push(`🎁 Brinde: ${gifts}x Decante ${$('#giftSelect').value} 5 ml`);const notes=$('#notes').value.trim();const text=[`Olá! Gostaria de fazer este pedido na Lojinha da Karla:`,``,...lines,``,`Total estimado: ${money(total)}`,`Pagamento: ${payment}`,notes?`Observações: ${notes}`:'','',`Pode confirmar a disponibilidade e a entrega?`].filter(Boolean).join('\n');window.open(`https://wa.me/5521999000170?text=${encodeURIComponent(text)}`,'_blank')}

document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)addItem(add.dataset.add);const qty=e.target.closest('[data-qty]');if(qty){const x=cart.find(i=>i.id===qty.dataset.qty);if(x){const delta=Number(qty.dataset.delta),limit=stockLimits[x.id];if(delta>0&&limit&&x.qty>=limit){toast('Esta é a última unidade disponível');return}x.qty+=delta;if(x.qty<=0)cart=cart.filter(i=>i.id!==x.id);save()}}const filter=e.target.closest('[data-filter]');if(filter){active=filter.dataset.filter;renderFilters();renderProducts()}const kit=e.target.closest('[data-kit]');if(kit){const k=kits.find(x=>x.id===kit.dataset.kit);cart.push({id:k.id,name:k.name,price:k.basePrice,volume:'Kit',type:'kit',qty:1});save();toggleCart(true)}if(e.target.closest('.close-link'))toggleCart(false)});
$('#search').addEventListener('input',e=>{query=e.target.value.toLowerCase().trim();renderProducts()});$('#sort').addEventListener('change',renderProducts);document.querySelectorAll('[name="payment"]').forEach(r=>r.addEventListener('change',renderCart));$('#openCart').onclick=()=>toggleCart(true);$('#closeCart').onclick=()=>toggleCart(false);$('#overlay').onclick=()=>toggleCart(false);$('#checkout').onclick=checkout;$('.menu-button').onclick=e=>{const open=$('.nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)};document.querySelectorAll('.nav a').forEach(a=>a.onclick=()=>$('.nav').classList.remove('open'));$('#year').textContent=new Date().getFullYear();renderFilters();renderProducts();renderDecants();renderKits();renderCart();
